#!/usr/bin/env python3
"""Writes the ESCargot mark as SVG, for android/art/make.sh to rasterise.

A logarithmic spiral, r = a * e^(b*theta): a snail shell, for ESCargot, in
this fork's own accent colour. No upstream artwork is involved.

The taper is why this is a script rather than a hand-drawn file. SVG 1.1
cannot vary a stroke width along a path, and the first attempt faked it with
a second heavier pass over the outer half -- which left a detached arc where
that pass began, and read as a wave rather than a shell. Drawing the spiral
as overlapping segments of increasing width gives a real taper.
"""

import math

ACCENT = "#00A1DD"      # lightAccent, appstyle.cpp
HIGHLIGHT = "#E5CF33"   # tertiary1
GROUND = "#272727"      # darkBackground


def spiral_pts(turns, a, b, cx, cy, rot, steps=600):
    pts = []
    tmax = turns * 2 * math.pi
    for i in range(steps + 1):
        t = tmax * i / steps
        r = a * math.exp(b * t)
        pts.append((cx + r * math.cos(t + rot), cy + r * math.sin(t + rot)))
    return pts


def tapered(pts, w0, w1, segs=28):
    out = []
    n = len(pts)
    for s in range(segs):
        i0 = int(n * s / segs)
        i1 = min(int(n * (s + 1) / segs) + 1, n)
        chunk = pts[i0:i1]
        if len(chunk) < 2:
            continue
        # Slightly superlinear, so the apex stays fine and the outer whorl
        # carries the weight.
        w = w0 + (w1 - w0) * (s / float(segs - 1)) ** 1.25
        d = "M %.2f %.2f " % chunk[0] + " ".join(
            "L %.2f %.2f" % p for p in chunk[1:])
        out.append((d, w))
    return out


def mark(size, ground, cx, cy, a, b, w0, w1, turns=2.45, rot=-0.6):
    pts = spiral_pts(turns, a, b, cx, cy, rot)
    paths = "\n".join(
        '    <path d="%s" stroke="%s" stroke-width="%.2f"/>' % (d, ACCENT, w)
        for d, w in tapered(pts, w0, w1))
    apex = pts[0]

    return '''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">
  <!-- Generated by android/art/mark.py. Do not edit. -->
%s  <g fill="none" stroke-linecap="round">
%s
  </g>
  <circle cx="%.2f" cy="%.2f" r="%.2f" fill="%s"/>
</svg>
''' % (size, size, size, size, ground, paths,
       apex[0], apex[1], w0 * 0.62, HIGHLIGHT)


def splash(w, h):
    """Ground plus the mark, centred, at a tenth of the short edge."""
    short = min(w, h)
    scale = short * 0.34
    cx, cy = w / 2.0, h / 2.0
    pts = spiral_pts(2.45, scale * 0.0175, 0.21, cx, cy, -0.6)
    paths = "\n".join(
        '    <path d="%s" stroke="%s" stroke-width="%.2f"/>'
        % (d, ACCENT, wd * scale / 48.0)
        for d, wd in tapered(pts, 2.2, 9.4))
    apex = pts[0]

    return '''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">
  <!-- Generated by android/art/mark.py. Do not edit. -->
  <rect width="%d" height="%d" fill="%s"/>
  <g fill="none" stroke-linecap="round">
%s
  </g>
  <circle cx="%.2f" cy="%.2f" r="%.2f" fill="%s"/>
</svg>
''' % (w, h, w, h, w, h, GROUND, paths,
       apex[0], apex[1], 2.2 * 0.62 * scale / 48.0, HIGHLIGHT)


def main():
    # Adaptive foreground: art inside the central 72 of a 108 canvas.
    open('icon_fg.svg', 'w').write(
        mark(108, "", 54.0, 55.0, a=1.5, b=0.205, w0=2.0, w1=8.6))

    square = '  <rect width="96" height="96" rx="18" fill="%s"/>\n' % GROUND
    circle = '  <circle cx="48" cy="48" r="48" fill="%s"/>\n' % GROUND

    open('icon_legacy.svg', 'w').write(
        mark(96, square, 48.0, 49.0, a=1.7, b=0.21, w0=2.2, w1=9.4))
    open('icon_round.svg', 'w').write(
        mark(96, circle, 48.0, 49.0, a=1.7, b=0.21, w0=2.2, w1=9.4))

    open('splash_land.svg', 'w').write(splash(1500, 1000))
    open('splash_port.svg', 'w').write(splash(1000, 1500))


if __name__ == "__main__":
    main()
